// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDphuDtJnRqquZ5MNB127lOlIV_Cg23C9s',
    appId: '1:699299586814:web:0d94eb46721b3da216fbaf',
    messagingSenderId: '699299586814',
    projectId: 'university-event-helper-22586',
    authDomain: 'university-event-helper-22586.firebaseapp.com',
    storageBucket: 'university-event-helper-22586.firebasestorage.app',
    measurementId: 'G-XJMBFPHJ6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY8qY9W2WrweoKnqznLVOq2JHvfeJmPJI',
    appId: '1:699299586814:android:f48f09f5a980c43216fbaf',
    messagingSenderId: '699299586814',
    projectId: 'university-event-helper-22586',
    storageBucket: 'university-event-helper-22586.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo0L-Th_jR2TkBOsj6IcckBfIZHihpzX8',
    appId: '1:699299586814:ios:68bf03932e70df3416fbaf',
    messagingSenderId: '699299586814',
    projectId: 'university-event-helper-22586',
    storageBucket: 'university-event-helper-22586.firebasestorage.app',
    iosBundleId: 'com.example.eventHelper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo0L-Th_jR2TkBOsj6IcckBfIZHihpzX8',
    appId: '1:699299586814:ios:68bf03932e70df3416fbaf',
    messagingSenderId: '699299586814',
    projectId: 'university-event-helper-22586',
    storageBucket: 'university-event-helper-22586.firebasestorage.app',
    iosBundleId: 'com.example.eventHelper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDphuDtJnRqquZ5MNB127lOlIV_Cg23C9s',
    appId: '1:699299586814:web:b8624ef2abed8b4c16fbaf',
    messagingSenderId: '699299586814',
    projectId: 'university-event-helper-22586',
    authDomain: 'university-event-helper-22586.firebaseapp.com',
    storageBucket: 'university-event-helper-22586.firebasestorage.app',
    measurementId: 'G-E8GMQ40F7W',
  );
}
